# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dgHfOVcZBxDLGRxSsKPmTDheeiEyTrs
"""

# === 1. Install Dependencies ===
# Run this in Colab or terminal if not installed
# !pip install gradio pandas numpy tensorflow scikit-learn plotly

# === 2. Imports ===
import gradio as gr
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
import plotly.graph_objects as go

# === 3. Generate Synthetic Dataset ===
np.random.seed(42)
days = pd.date_range(start="2023-01-01", periods=365)
data = pd.DataFrame({
    "Date": days,
    "Temperature": np.random.uniform(15, 40, 365),
    "Sunlight_Hours": np.random.uniform(4, 12, 365),
    "Humidity": np.random.uniform(20, 80, 365),
    "Wind_Speed": np.random.uniform(1, 15, 365)
})
data["Energy_Output"] = (
    0.4 * data["Temperature"]
    + 1.8 * data["Sunlight_Hours"]
    - 0.2 * data["Humidity"]
    + 0.5 * data["Wind_Speed"]
    + np.random.normal(0, 2, 365)
)

# === 4. Preprocess Data ===
scaler = MinMaxScaler()
scaled = scaler.fit_transform(data[["Temperature", "Sunlight_Hours", "Humidity", "Wind_Speed", "Energy_Output"]])

def create_sequences(dataset, seq_len=7, forecast_horizon=7):
    X, y = [], []
    for i in range(len(dataset) - seq_len - forecast_horizon):
        X.append(dataset[i:i+seq_len, :-1])
        y.append(dataset[i+seq_len:i+seq_len+forecast_horizon, -1])
    return np.array(X), np.array(y)

X, y = create_sequences(scaled)
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# === 5. Build & Train LSTM Model ===
model = Sequential([
    LSTM(64, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    Dense(32, activation='relu'),
    Dense(7)  # next 7 days
])
model.compile(optimizer='adam', loss='mse')
model.fit(X_train, y_train, epochs=25, batch_size=8, verbose=0)

# === 6. Forecast Function ===
def forecast_energy(temp_list, sun_list, hum_list, wind_list):
    # Ensure all inputs are lists of length 7
    temp_list = temp_list[:7]
    sun_list = sun_list[:7]
    hum_list = hum_list[:7]
    wind_list = wind_list[:7]

    seq = np.array(list(zip(temp_list, sun_list, hum_list, wind_list)))
    seq_scaled = scaler.transform(np.hstack([seq, np.zeros((7,1))]))
    seq_scaled = np.expand_dims(seq_scaled[:, :-1], axis=0)

    # Predict next 7 days
    pred_scaled = model.predict(seq_scaled)[0]

    # Convert back to original scale
    dummy = np.zeros((7, 5))
    dummy[:, -1] = pred_scaled
    pred_actual = scaler.inverse_transform(dummy)[:, -1]

    # Plotly Interactive Graph
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=[f"Day {i+1}" for i in range(7)],
        y=pred_actual,
        mode="lines+markers",
        name="Predicted Energy (kW)",
        line=dict(width=3),
        marker=dict(size=8)
    ))
    fig.update_layout(
        title="🔋 Predicted Renewable Energy Output (Next 7 Days)",
        xaxis_title="Future Days",
        yaxis_title="Energy Output (kW)",
        template="plotly_white",
        height=400
    )

    next_day = pred_actual[0]
    return f"Predicted Next Day Energy Output: {next_day:.2f} kW", fig

# === 7. Gradio Web App ===
with gr.Blocks(title="Renewable Energy Forecasting App") as app:
    gr.Markdown("## 🌞 Renewable Energy Forecasting (LSTM + Interactive Graph)")
    gr.Markdown("Enter environmental data for the past 7 days to predict renewable energy for the next 7 days.")

    with gr.Row():
        temp_input = gr.Dataframe(headers=[f"Day{i+1}" for i in range(7)], row_count=1, col_count=7, label="Temperature (°C)")
        sun_input = gr.Dataframe(headers=[f"Day{i+1}" for i in range(7)], row_count=1, col_count=7, label="Sunlight Hours")
    with gr.Row():
        hum_input = gr.Dataframe(headers=[f"Day{i+1}" for i in range(7)], row_count=1, col_count=7, label="Humidity (%)")
        wind_input = gr.Dataframe(headers=[f"Day{i+1}" for i in range(7)], row_count=1, col_count=7, label="Wind Speed (m/s)")

    predict_btn = gr.Button("🔮 Forecast Energy Output")
    text_output = gr.Textbox(label="Next Day Prediction")
    plot_output = gr.Plot(label="7-Day Forecast Graph")

    predict_btn.click(
        fn=lambda t, s, h, w: forecast_energy(
            np.array(t).flatten().tolist(),
            np.array(s).flatten().tolist(),
            np.array(h).flatten().tolist(),
            np.array(w).flatten().tolist(),
        ),
        inputs=[temp_input, sun_input, hum_input, wind_input],
        outputs=[text_output, plot_output],
    )

    gr.Markdown("💚 Created by Tharanee | Renewable Energy Research Assistant 🌍")

app.launch()